- name: Install MariaDB
  hosts: sql
  become: true
  
  tasks:

	
    - name: Install MariaDB Packages
      apt: name={{item}} state=installed default_release=trusty update_cache=yes
      with_items:
        - mariadb-client
        - mariadb-common
        - mariadb-server

    - name: Create MariaDB Directories
      file: path=/data/{{item}} state=directory owner=mysql group=mysql recurse=yes
      with_items:
        - db
        - log

    - name: Count files in /data/db
      find:
        path=/data/db
        patterns='\*'
      register: db_files

    - name: Run mysql_install_db only if /data/db is empty
      command: mysql_install_db --datadir=/data/db
      when: db_files.matched|int == 0
      
    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes