- hosts: all
  become: true
  tasks:

  tasks:
    - name: Clone template
      community.general.proxmox_kvm:
        node: pve
        api_user: root@pam
        api_password: "{{PW}}"
        api_host: 192.168.0.10
        clone: ubuntu-cloud
        newid: "{{NI}}"
        name: "{{HN}}"
        full: false
        format: unspecified
        timeout: 500

    - name: Warte 15 Sekunden
      pause:
        seconds: 15
    
    - name: Update IP
      community.general.proxmox_kvm:
        node: pve
        api_user: root@pam
        api_password: "{{PW}}"
        api_host: 192.168.0.10
        vmid: "{{NI}}"
        ipconfig:
          ipconfig0: 'ip={{IP}}/24,gw=192.168.0.1'
        memory: "{{MM}}"
        update: yes

    - name: Update disk
      community.general.proxmox_disk:
        #node: pve
        api_user: root@pam
        api_password: "{{PW}}"
        api_host: 192.168.0.10
        vmid: "{{NI}}"
        disk: scsi0
        size: "+{{GB}}G"
        state: resized
        
