- hosts: all
  become: true
  tasks:

  tasks:
    - name: Clone template
      community.general.proxmox_kvm:
        node: pve
        api_user: root@pam
        api_password: "{{PW}}"
        api_host: 192.168.0.10
        clone: ubuntu-cloud
        name: "{{HN}}"
        full: false
        format: unspecified
        timeout: 500

    - name: Update
      community.general.proxmox_kvm:
        node: pve
        api_user: root@pam
        api_password: "{{PW}}"
        api_host: 192.168.0.10
        name: server1
        ipconfig:
          ipconfig0: 'ip={{IP}}/24,gw=192.168.0.1'
        update: yes
