---
- name: Create new LXC container in Proxmox
  hosts: all
  tasks:
    - name: 'Create LXC Container'
      proxmox:
          vmid: "{{NI}}" # Specifying Container ID
          node: pve
          api_user: root@pam
          api_password: "{{PW}}"
          api_host: 192.168.0.10
          hostname: 'ansible-lxc' # Container hostname
          password: 123456
          cores: '1'
          cpus: '1'
          cpuunits: '1000'
          ostemplate: 'local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz' # Or use local:vztmpl/...
          storage: 'local' # Or use 'local'
          disk: '8'
          memory: '512'
          unprivileged: true
          nameserver: '192.168.0.35'
          netif: '{"net0":"name=eth0,ip=192.168.0.38/24,gw=192.168.0.1,bridge=vmbr0"}'
          state: 'present'

