---
- name: Create new LXC container in Proxmox
  hosts: all
  tasks:
    - name: 'Create LXC Container'
      proxmox:
          vmid: "{{NI}}" # Specifying Container ID
          api_user: root # Proxmox user
          api_password: "{{PW}}" # Password in plaintext !!!
          api_host: 192.168.0.10 # Proxmox hostname
          password: "{{PW}}" # Password in plaintext !!!
          hostname: 'ansible-lxc' # Container hostname
          node: 'pve' # Name of Proxmox host
          cores: '1'
          cpus: '1'
          #cpuunits: '1000'
          ostemplate: 'local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz' # Or use local:vztmpl/...
          storage: 'local' # Or use 'local'
          disk: '8'
          memory: '512'
          nameserver: '192.168.0.35'
          netif: '{"net0":"name=eth0,ip=192.168.0.38/24,gw=192.168.0.1,bridge=vmbr0"}'
          state: 'present'

