---
- name: Create user torsten and set password
  hosts: lxc
  become: yes

  tasks:
    - name: Add user torsten
      user:
        name: "{{USR}}"
        state: present
        update_password: always
        groups: sudo
        password: "{{ PW | password_hash('sha512') }}"
