---
- name: Create user torsten and set password
  hosts: lxc
  become: yes

  tasks:
    - name: Add user torsten
      user:
        name: "{{USR}}"
        shell: /bin/bash
        state: present
        update_password: always
        groups: sudo
        group: users
        append: true
        password: "{{ PW | password_hash('sha512') }}"
