---
- name: Update Ubuntu, install Nginx, and start Nginx service
  hosts: lxc
  become: yes

  tasks:
    - name: Update Ubuntu
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
