---
- name: Create user torsten and set password
  hosts: lxc
  become: yes

  tasks:
    - name: Add user torsten
      user:
        name: "{{USR}}"
        state: present
        update_password: always
        groups: sudo

    - name: Set password for user torsten
      ansible.builtin.shell: echo "{{PW}}" | chpasswd
