---
- name: Aktualisiere Ubuntu-Systeme
  hosts: newone
  become: true

  tasks:
    - name: Aktualisiere die Paketliste
      apt:
        update_cache: yes
      tags: update
      
    - name: install updates
      tags: update
      apt:
        upgrade: yes
        update_cache: yes
      tags: update

     - name: install qemu guest agent
       apt:
         name: qemu-guest-agent
         state: present

     - name: Führe das Systemupgrade durch
       apt:
         upgrade: dist
         autoremove: yes
         autoclean: yes
       tags: upgrade

     - name: reboot host
       reboot:
