---
- hosts: newone
  gather_facts: false
  become: yes

  tasks:
    - name: update apt cache
      command: apt update

    - name: install qemu guest agent
      apt:
        name: qemu-guest-agent
        state: present

    - name: upgrade all packages
      command: apt upgrade -y

    - name: XKBLAYOUT DE, fuer Tastaturlayout deutsch
      lineinfile:
        path: /etc/default/keyboard
        regexp: '^XKBLAYOUT='
        line: 'XKBLAYOUT="de"'
        
    - name: Ermögliche die Authentifizierung per Passwort
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
        
    - name: reboot host
      reboot:
