---
- hosts: newone
  gather_facts: false
  become: yes

  tasks:
    - name: update apt cache
      command: apt update

    - name: install qemu guest agent
      apt:
        name: qemu-guest-agent
        state: present

    - name: upgrade all packages
      command: apt upgrade -y

    - name: Fuehre den Befehl setxkbmap aus, fuer Tastaturlayout deutsch
      shell: setxkbmap de
    
    - name: reboot host
      reboot:
