---
- name: Passwort eines Benutzers ändern
  hosts: all
  become: true
  tasks:
    - name: Passwort für den Benutzer ändern
      user:
        name: torsten
        update_password: always
        password: "{{ '+++++' | password_hash('sha512') }}"
