---
- name: Passwort eines Benutzers 채ndern
  hosts: your_target_host
  become: yes  # Um als Root-Benutzer auszuf체hren
  tasks:
    - name: Passwort f체r den Benutzer 채ndern
      user:
        name: your_username
        update_password: always
        password: "{{ 'Zulu12' | password_hash('sha512') }}"
