---
- name: Passwort eines Benutzers ändern
  hosts: all
  become: true
  tasks:
    - name: Passwort für den Benutzer ändern
      user:
        name: your_username
        update_password: always
        password: "{{ 'Zulu12!' | password_hash('sha512') }}"
