---
- name: Aktualisiere Ubuntu-Systeme
  hosts: sql
  become: true

  tasks:
    - name: Aktualisiere die Paketliste
      apt:
        update_cache: yes
      tags: update
      
    - name: install updates
      tags: update
      apt:
        upgrade: yes
        update_cache: yes
      tags: update
     

    - name: Führe das Systemupgrade durch
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: upgrade
