---
- name: Wake-on-LAN playbook
  hosts: all
  become: yes
  tasks:
    - name: Ensure wakeonlan is installed
      ansible.builtin.package:
        name: wakeonlan
        state: present

    - name: Send WoL packet to Proxmox Server
      ansible.builtin.command: wakeonlan 60:32:b1:d8:e6:7b
      args:
        chdir: /usr/bin/
      ignore_errors: true
