---
- hosts: all
  become: true
  vars:
    root_password: "12345"
    db_name: app
    db_user: appuser
    db_password: "12345"
    db_user_tv: "torsten"
  
  tasks:
    - name: Install config-parser
      apt:
        name: pkg-config
        state: present
    
    - name: Install libmysqlclient-dev
      apt:
        name: libmysqlclient-dev
        state: present
    
    - name: Install python3-dev on the target server
      apt:
        name: python3-dev
        state: present
        
    - name: Install pip3 on the target server
      apt:
        name: python3-pip
        state: present
     
    - name: Install pip on the target server
      apt:
        name: pip
        state: present
    
    - name: Install mysqlclient using pip
      pip:
        name: mysqlclient
        executable: pip3
      register: pip_install_result

    - name: Check if mysqlclient was installed
      debug:
        var: pip_install_result

    #- name: Import MySQLdb in Python (optional)
      #command: python3 -c "import MySQLdb"
      #ignore_errors: yes    
    
    
    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present

    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure MariaDB server
      mysql_user:
        name: root
        host: localhost
        password: "{{ root_password }}"
        login_user: root
        login_password: ""
        priv: "*.*:ALL,GRANT"
        
    - name: Run mysql_secure_installation
      shell: mysql_secure_installation
      args:
        stdin: |
          Y
          {{ root_password }}
          {{ root_password }}
          Y
          Y
          Y
          Y
    
    

 
    - name: Create the MySQL user "torsten" with superuser privileges
      mysql_user:
        name: "{{ db_user_tv }}"
        host: localhost
        password: "{{ root_password }}"
        priv: "*.*:ALL,GRANT"
        state: present

    #- name: Reload privileges
      #mysql_db:
        #name: "*.*"
        #state: flush privileges
 
    - name: Create the database "app"
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create the MySQL user "appuser"
      mysql_user:
        name: "{{ db_user }}"
        host: localhost
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present

    #- name: Reload privileges
      #mysql_db:
        #name: "*.*"
        #state: flush privileges